# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10)),
                ('nation', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(blank=True, max_length=10)),
                ('name', models.TextField(blank=True)),
                ('lg_qf', models.TextField(blank=True)),
                ('pg_qf', models.TextField(blank=True)),
                ('people', models.CharField(blank=True, max_length=10)),
                ('term', models.CharField(blank=True, max_length=10)),
                ('detail', models.CharField(blank=True, max_length=10)),
                ('link_school', models.TextField(blank=True)),
            ],
        ),
    ]
