# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Univs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_number', models.CharField(max_length=6)),
                ('uni_nation', models.CharField(blank=True, max_length=10)),
                ('uni_location', models.CharField(blank=True, max_length=10)),
                ('uni_name', models.TextField()),
                ('uni_language', models.TextField(blank=True)),
                ('uni_people', models.CharField(blank=True, max_length=1)),
                ('uni_term', models.CharField(blank=True, max_length=1)),
                ('uni_logo', models.TextField(blank=True)),
                ('uni_map', models.TextField(blank=True)),
                ('uni_site', models.TextField(blank=True)),
                ('uni_address', models.TextField(blank=True)),
                ('uni_found', models.TextField(blank=True)),
                ('uni_area', models.TextField(blank=True)),
                ('uni_nos', models.TextField(blank=True)),
                ('uni_major', models.TextField(blank=True)),
                ('uni_qualification', models.TextField(blank=True)),
                ('uni_etc', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NatData',
        ),
    ]
