# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0002_auto_20170528_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univs',
            name='uni_logo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='univs',
            name='uni_site',
            field=models.URLField(blank=True),
        ),
    ]
