# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 17:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0003_auto_20170530_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtcMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 6, 9, 17, 2, 4, 781384, tzinfo=utc))),
            ],
        ),
    ]
