# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0004_etcmod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='univs',
            name='uni_area',
        ),
        migrations.RemoveField(
            model_name='univs',
            name='uni_etc',
        ),
        migrations.RemoveField(
            model_name='univs',
            name='uni_found',
        ),
        migrations.RemoveField(
            model_name='univs',
            name='uni_nos',
        ),
        migrations.AlterField(
            model_name='etcmod',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 9, 17, 4, 57, 53768, tzinfo=utc)),
        ),
    ]
