# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0005_auto_20170610_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etcmod',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 9, 17, 5, 47, 328698, tzinfo=utc)),
        ),
    ]
