# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0006_auto_20170610_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etcmod',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
