# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170528_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='Title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
