# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170528_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Title',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='Title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
